name: "Setup rust"
description: "Checkout du code et installation de rust"
runs:
  using: "composite"
  steps:
    - name: install rust
      run: sudo apt update && sudo apt install -y rustup
      shell: bash
    - name: Cache Rust
      uses: Swatinem/rust-cache@v2