name: check quality workflow
on:
  pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code                                                                                                  
        uses: actions/checkout@v4  
      - name: install rust
        run: sudo apt update && sudo apt install rustup
      - name: check code
        run: cargo check
