name: CI - Release & Documentation

# Se declenche uniquement quand un push arrive sur main (= quand une PR est mergee)
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  construire-publier-et-documenter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git . && git checkout ${{ github.sha }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz \
            | sudo tar -xJ --strip-components=1 -C /usr/local/bin typst-x86_64-unknown-linux-musl/typst

      - name: Build release
        run: make release

      - name: Build doc
        run: make doc
