name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # PR cible main -> compile release + doc
  build-release-and-doc:
    # Temporairement commenté pour tester sur notre branche sans ouvrir de PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      # Typst pour generer le pdf (ajout de sudo pour éviter les erreurs de permission)
      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz \
            | sudo tar -xJ --strip-components=1 -C /usr/local/bin typst-x86_64-unknown-linux-musl/typst

      - name: Build release
        run: make release

      - name: Build doc
        run: make doc

  # Autres cas -> check clippy + tests unitaires
  check-and-test:
    # Temporairement commenté pour tester les deux jobs en même temps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}

      - name: Run check & clippy
        run: make check

      - name: Run tests
        run: make test
