name: CI - Checks & Tests

# Se declenche sur toutes les PR qui ciblent main (et les autres branches si besoin)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verification-et-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git . && git checkout ${{ github.sha }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          rustup component add clippy
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run check & clippy
        run: make check

      - name: Run tests
        run: make test
