name: propage changement
on:
  pull_request:
    # types: [closed]
permissions:
  pull-requests: write
jobs:
  echo_test_information:
    runs-on : ubuntu-latest
    steps:
        - name: echo base and head github
          run: "echo head :/ ${{github.head_ref}}/t base :/ ${{github.base_ref}}"
        - name: afficher labels
          env:
            LABELS: ${{toJson(github.event.pull_request.labels.*.name)}}
          run: echo "$LABELS" | jq -r '.[]'
  propagate_with_label:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bug/')
    steps:
      - name: echo test for test
        env:
            HEAD_REF: ${{github.head_ref}}
            LABELS: ${{toJson(github.event.pull_request.labels.*.name)}}
        run: |
          TARGETS=$(echo "$LABELS" | jq -r '.[] | select(startswith("propagate:")) | ltrimstr("propagate:")')

          if [ -n "$TARGETS" ]; then
          echo "$TARGETS" | while read -r target; do
            gh pr create \
              --base "$target" \
              --head "$HEAD_REF" \
              --title "$target" \
          done

         
