name: propage changement
on:
  pull_request:
    # types: [closed]
jobs:
  echo_test_information:
    runs-on : ubuntu-latest
    steps:
        - name: echo base and head github
          run: "echo head :/ ${{github.head_ref}}/t base :/ ${{github.base_ref}}"
        - name: afficher labels
          env:
            LABELS: ${{toJson(github.event.pull_request.labels.*.name)}}
          run: echo "$LABELS" | jq -r '.[]'
  propagate_with_label:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bug/')
    steps:
      - name: echo test for test
        env:
            LABELS: ${{toJson(github.event.pull_request.labels.*.name)}}
        run: |
          TARGETS=$(echo "$LABELS" | jq -r '.[] | select(startswith("propagate:")) | ltrimstr("propagate:")')

          echo "$TARGETS" | while read -r target; do
            echo "target is $target"
          done
          
         
