name: release-artifacts

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Acquire code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          sudo apt update
          sudo apt install -y rustup
          rustup toolchain install stable

      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build Simeis binary
        run: cargo build --release -p simeis-server

      - name: Prepare Debian package structure
        run: |
          mkdir -p packaging/debian/usr/bin
          mkdir -p packaging/debian/usr/share/man/man1
          mkdir -p packaging/debian/etc/systemd/system
          mkdir -p packaging/debian/DEBIAN

          # Copier le binaire (simeis-server -> simeis)
          cp target/release/simeis-server packaging/debian/usr/bin/simeis

          # Copier les fichiers Debian
          cp packaging_src/control packaging/debian/DEBIAN/control
          cp packaging_src/postinst packaging/debian/DEBIAN/postinst
          cp packaging_src/prerm packaging/debian/DEBIAN/prerm
          cp packaging_src/postrm packaging/debian/DEBIAN/postrm
          cp packaging_src/simeis.service packaging/debian/etc/systemd/system/simeis.service
          cp packaging_src/simeis.1 packaging/debian/usr/share/man/man1/simeis.1

          chmod 755 packaging/debian/DEBIAN/postinst
          chmod 755 packaging/debian/DEBIAN/prerm
          chmod 755 packaging/debian/DEBIAN/postrm

      - name: Build Debian package
        run: dpkg-deb --build packaging/debian simeis.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: simeis-debian
          path: simeis.deb

      - name: Release the new binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          prerelease: true
          name: "Latest Commit That Compiles"
          body: |
            Built from commit ${{ env.GIT_HASH }}
          files: simeis.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
